version: '3'
services:
  cache:
    container_name: ice-cream-cache
    image: 'redis'
    ports:
      - '6379:6379'
  app:
    container_name: ice-cream-api
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - cache
    links:
      - cache
    env_file:
      - ./.env
    environment:
      - CACHE_DRIVER=redis
      - CACHE_HOST=cache
      - CACHE_PORT=6379
